### ISSUE TITLE
Reduce False Positives

### ISSUE THREAD

**Issue by MaleshwarSastri** [aosokin/os2d#1]
Hey !
I get a lot of false positives during detection and i used your model that you gave.Can u suggest a solution to reduce the false positives?
Thanks.

**Comment by raghavgurbaxani** [comment]
Same issue here, lots of false positives. 
Also to the authors - is it suggested that the background for the target image should be white ?

**Comment by aosokin** [comment]
Hi, looking at your results I can suggest tweaking the parameters
`cfg.visualization.eval.max_detections`
`cfg.visualization.eval.score_threshold`
to setup a better threshold on the score and the number of detections to visualize.
Another thing to try would be to change nms_iou_threshold and nms_score_threshold parameters of the decoding function box_coder.decode_pyramid - those can cut down the number of detections you are getting.

**Comment by aosokin** [comment]
@raghavgurbaxani Specific to the dog example: my guess would be that flipping the class image left to right might improve the results (our method is not invariant to left-right flips os the class image).

> Also to the authors - is it suggested that the background for the target image should be white?

We do not have any specific suggestions like that. In our training set, most of the class images were on the white background but in some test sets the class images are on different backgrounds and the method still works.

**Comment by cjpark87** [comment]
@aosokin Having a similar problem here, too. I am testing out with a simple logo detection.

Here is some example of "nike" detection using your demo code.

![image](https://user-images.githubusercontent.com/2114730/83322573-a6817d00-a20d-11ea-8117-08941901acf4.png)
![image](https://user-images.githubusercontent.com/2114730/83322577-aa150400-a20d-11ea-85ab-099985f049ac.png)

It doesn't seem like it's detecting the logo.

Out of curiosity, I tested by assigning the same image for input and class image.

![image](https://user-images.githubusercontent.com/2114730/83322588-d16bd100-a20d-11ea-9b5a-55ca8cc30be6.png)
![image](https://user-images.githubusercontent.com/2114730/83322590-d597ee80-a20d-11ea-91b3-35d58ebe9744.png)

Could you provide a pointer to set the right threshold?

Thanks!

**Comment by aosokin** [comment]
Hi @cjpark87,
Thanks for your interest!
I guess there are two things you can do to improve results:
1) Searching across scales is difficult for OS2D. To be able to detect objects of different sizes OS2D relies on the image pyramid, which is not implemented in the demo. If ones gets the scale correct for the Nike logo it works:
Specifically, when I changed the constant 1500 hardcoded in the lines
```
h, w = get_image_size_after_resize_preserving_aspect_ratio(h=input_image.size[1],
                                                               w=input_image.size[0],
                                                               target_size=1500)
```
to 240 I immediately got this result (two detections correct one with the score 0.9 and another one with the score 0.4
![nike-logo-dets](https://user-images.githubusercontent.com/2099291/83327460-b9836400-a284-11ea-9f00-def6d1d99f85.jpg)

2) The second issue is a bit harder because of the feature matching under the hood of OS2D. The white background matches perfectly to white background, which creates confusion for detections.
To get the result below (2000 was the good scale) I did two tricks to the image with the logo:
- remove the black rectangle at the border to avoid border-to-border matches
- substitute the white pixels in the image with noise - I substituted the white pixels of class_images_th[0] with random noise from torch.randn(3)
![nike-shoe-dets](https://user-images.githubusercontent.com/2099291/83327467-cd2eca80-a284-11ea-92cf-226999676de7.jpg)

**Comment by cjpark87** [comment]
@aosokin Thanks! this was really helpful. I will play around with those variables in the future as well.

**Comment by aosokin** [comment]
@cjpark87 great, happy that was helpful! Good luck!
