### ISSUE TITLE
Why is loc_weight=0.0?

### ISSUE THREAD

**Issue by WeitaoVan** [aosokin/os2d#20]
Hi Aosokin,

In the [experiment for instre](https://github.com/aosokin/os2d/blob/96c488b3979c505b92245ccdab941fb01fdf99de/experiments/launcher_exp3_instre.py#L38)

The loc_weight is set to 0.0.  I can't figure out why we do not need the localization loss. 

Thank you.

**Comment by aosokin** [comment]
Hi, we discovered in our ablation study that when initializing TranformNet from Rocco et al. (our v2 model) it is not beneficial to use the localization loss. I think this is the case because transformations and bbox targets start to conflict and the transformation model gets damaged when training.
Best,
Anton

**Comment by WeitaoVan** [comment]
Thanks.

I also tried and found out that the loc_weight should be set to 0 for your v2 model.
