### ISSUE TITLE
TransformNet checkpoint load

### ISSUE THREAD

**Issue by JHevia23** [aosokin/os2d#23]
Hi! First of all, I really appreciate your work  and the high quality of your repository. I've been taking a look at it for some days now and I found it very well organized.

I saw that you made available the checkpoints for Rocco's TransformNet, however, I couldn't find the place where they're loaded when building the OS2D model. Could you point me at a specific folder to look for that checkpoint load?

By the way, I'm currently trying out other backbone architectures for feature extraction, have you experimented with other models besides ResNet?

Thanks!

**Comment by aosokin** [comment]
Hi, thank you for your kind words!

> I saw that you made available the checkpoints for Rocco's TransformNet, however, I couldn't find the place where they're loaded when building the OS2D model. Could you point me at a specific folder to look for that checkpoint load?

When initializing the V2 model we loaded the original weights of Rocco et al. with this function:
https://github.com/aosokin/os2d/blob/96c488b3979c505b92245ccdab941fb01fdf99de/os2d/modeling/model.py#L389-L426

When loading our checkpoints the transformer parameters are just regular parameters of a pytorch model. Btw, our V2-init checkpoint contains the weights of Rocco et al. converted to our format. It might be worth comparing those if you are interested in the details.

> By the way, I'm currently trying out other backbone architectures for feature extraction, have you experimented with other models besides ResNet?

We have not really tried that, partly because one might need to rerun codes of Rocco et al.  (their pretaining on synthetic data) to retrain TransformNet to be compatible with other backbones. But I see not real reason why that shouldn't work.

Best,
Anton
