### ISSUE TITLE
Some ideas about training with typical object detection datasets.

### ISSUE THREAD

**Issue by zhangliukun** [aosokin/os2d#32]
Hi, thanks for you greate work. I have some ideas about training the model with the typical OD datasets like VOC or COCO.
Since the grozi3.2k datasets needs labeled carefully and it is time consuming to get new data, I wondering if we could use the OD annotations directly.
Here are the steps:
1. Get the input image and it's bbox labels as a input image
2. Random select  one class in the labels and crop it out as a class-image.
3. Considering the case that objects may be looks very different with the same class int the COCO or VOC, we could  treat them as one class for semantic level one-shot OD or treat them as different for instance level one-shot OD.
4. So we get the input image and the class-image and train it. 

Have you tried similar idea and could give me some advice?

**Comment by aosokin** [comment]
Hi, we did try to use cropped objects from images as positives - this is done with the mine_extra_class_images flag. But if I remember correctly it did not really help for all datasets except INSTRE. I think it is the case because for main validation we used our version of Grozi where class images came with the white background.

We have never tried going furhter in this direction for COCO or VOC but I think it is worth exploring.
